### ISSUE TITLE
Error when .berkshelf directory does not exist

### ISSUE THREAD

**Issue by wsoula** [jbartko/multi_chef#1]
Don't know if you want to fix it in the code or just add it to the README.  I had to manually create the `.berkshelf` directory for it to succeed.
```
eval "$(./multi_chef.rb -a api.chef.io -o di -u wsoula)"
./multi_chef.rb:178:in `initialize': No such file or directory @ rb_sysopen - /Users/william.soula/.berkshelf/config.json (Errno::ENOENT)
	from ./multi_chef.rb:178:in `open'
	from ./multi_chef.rb:178:in `<main>'
```

**Comment by jbartko** [comment]
Good catch! `multi_chef.rb` should probably test for the existence of the directory and create it as necessary.

**Comment by jbartko** [comment]
jbartko/multi_chef#2 *should* resolve this issue.
